name: 'Terraform'

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: read
  id-token: 'write'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
        working-directory: ./AIRS-infra

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2.0.0  
      with:
        workload_identity_provider: 'projects/470539605200/locations/global/workloadIdentityPools/airs-cicd-id-pool/providers/github'
        service_account: 'airs-cicd-sa@airs-509504.iam.gserviceaccount.com'
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
