#placeholder for infra deployment pipeline
name: Infrastructure Deloyment 
on: 
  push:
    branches: ["*"]
    
runs-on: ubuntu-latest

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform version
        run: terraform version